site_name: Arguing Predictors
site_url: ''
use_directory_urls: False

theme:
    name: mkdocs

nav:
    - Home: index.md
    - Installation: installation.md
    - Start: usage.md
    - The System: modify.md
    - Pre-trained models: pre-trained_models.md
    - Consensus: consensus.md
    - Evaluation: evaluation.md
