site_name: Arguing Predictors

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Modification Manual: modify.md
    - Pre-trained models: pre-trained_models.md
    - Consensus: consensus.md
