site_name: Arguing Predictors

theme:
    name: mkdocs

nav:
    - Home: index.md
    - Installation: installation.md
    - Start: usage.md
    - Modification Manual: modify.md
    - Pre-trained models: pre-trained_models.md
    - Data Import: dataloader.md
    - Consensus: consensus.md
    - Evaluation: evaluation.md
