site_name: Arguing Predictors
site_url: ""
use_directory_urls: False


theme:
        name: material
        palette:
                primary: black

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences        

nav:
    - Home: index.md
    - Installation: installation.md
    - Start: usage.md
    - The System: modify.md
    - Pre-Trained Models: pre-trained_models.md
    - Consensus: consensus.md
    - Predictors: individual.md
    - Evaluation: evaluation.md
